export const serviceValuesAccounting = {
  revenueSegments: {
    micro: '< $250K',
    small: '$250K - $500K',
    medium: '$500K - $1M',
    large: '$1M - $3M',
    enterprise: '$3M plus',
  },
  taxServices: {
    individualReturns: {
      all: {
        code: '416422',
        monthly: 20.83,
        yearly: 250,
        quantity: null,
        inclusion: 'Individual Returns ALL',
      },
    },
    businessReturns: {
      micro: {
        code: '416423',
        monthly: 62.5,
        yearly: 750,
        quantity: 1,
        inclusion: 'Micro < $250K',
      },
      small: {
        code: '416424',
        monthly: 125,
        yearly: 1500,
        quantity: 1,
        inclusion: 'Small < $500K',
      },
      medium: {
        code: '416425',
        monthly: 166.67,
        yearly: 2000,
        quantity: 1,
        inclusion: 'Medium < $1M',
      },
      large: {
        code: '416426',
        monthly: 250,
        yearly: 3000,
        quantity: 1,
        inclusion: 'Large < $3M',
      },
    },
    smsf: {
      micro: {
        code: '416416',
        monthly: 166.67,
        yearly: 2000,
        quantity: null,
        inclusion: 'SMSF - Micro < $250K',
      },
      small: {
        code: '416417',
        monthly: 166.67,
        yearly: 2000,
        quantity: null,
        inclusion: 'SMSF - Small < $500K',
      },
      medium: {
        code: '416418',
        monthly: 333.33,
        yearly: 4000,
        quantity: null,
        inclusion: 'SMSF - Medium < $1M',
      },
      large: {
        code: '416419',
        monthly: 500,
        yearly: 6000,
        quantity: null,
        inclusion: 'SMSF - Large < $3M',
      },
    },
    fbtReturns: {
      micro: {
        code: '416421',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'FBT - Micro < $250K',
      },
      small: {
        code: '416422',
        monthly: 62.5,
        yearly: 750,
        quantity: null,
        inclusion: 'FBT - Small < $500K',
      },
      medium: {
        code: '416423',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'FBT - Medium < $1M',
      },
      large: {
        code: '416424',
        monthly: 125,
        yearly: 1500,
        quantity: null,
        inclusion: 'FBT - Large < $3M',
      },
    },
    bas: {
      micro: {
        code: '416426',
        monthly: 12.5,
        yearly: 150,
        quantity: 4,
        inclusion: 'BAS - Micro < $250K (per return)',
      },
      small: {
        code: '416427',
        monthly: 12.5,
        yearly: 150,
        quantity: 4,
        inclusion: 'BAS - Small < $500K (per return)',
      },
      medium: {
        code: '416428',
        monthly: 16.67,
        yearly: 200,
        quantity: 4,
        inclusion: 'BAS - Medium < $1M (per return)',
      },
      large: {
        code: '416429',
        monthly: 25,
        yearly: 300,
        quantity: 4,
        inclusion: 'BAS - Large < $3M (per return)',
      },
    },
    ias: {
      micro: {
        code: '416431',
        monthly: 8.33,
        yearly: 100,
        quantity: null,
        inclusion: 'IAS - Micro < $250K (per return)',
      },
      small: {
        code: '416432',
        monthly: 8.33,
        yearly: 100,
        quantity: null,
        inclusion: 'IAS - Small < $500K (per return)',
      },
      medium: {
        code: '416433',
        monthly: 10.42,
        yearly: 125,
        quantity: null,
        inclusion: 'IAS - Medium < $1M (per return)',
      },
      large: {
        code: '416434',
        monthly: 12.5,
        yearly: 150,
        quantity: null,
        inclusion: 'IAS - Large < $3M (per return)',
      },
    },
    tpar: {
      micro: {
        code: '416436',
        monthly: 18.33,
        yearly: 220,
        quantity: null,
        inclusion: 'TPAR - Micro < $250K (per return)',
      },
      small: {
        code: '416437',
        monthly: 18.33,
        yearly: 220,
        quantity: null,
        inclusion: 'TPAR - Small < $500K (per return)',
      },
      medium: {
        code: '416438',
        monthly: 18.33,
        yearly: 220,
        quantity: null,
        inclusion: 'TPAR - Medium < $1M (per return)',
      },
      large: {
        code: '416439',
        monthly: 20.83,
        yearly: 250,
        quantity: null,
        inclusion: 'TPAR - Large < $3M (per return)',
      },
    },
  },
  corporateSecretarial: {
    asicAnnualReturn: {
      code: '416590',
      monthly: 33.33,
      yearly: 400,
      quantity: null,
      inclusion: 'ASIC Annual Return',
    },
    asicFormsLodgements: {
      code: '416591',
      monthly: 12.5,
      yearly: 150,
      quantity: null,
      inclusion: 'ASIC Forms Lodgements',
    },
  },
  atoPaymentPlans: {
    basicPlans: {
      code: '416600',
      monthly: null,
      yearly: 500,
      quantity: null,
      inclusion: 'Basic plans',
    },
    hardshipPlans: {
      code: '416601',
      monthly: null,
      yearly: 1000,
      quantity: null,
      inclusion: 'Longer term & hardship plans',
    },
  },
  payrollServices: {
    workersCompensation: {
      micro: {
        code: '416441',
        monthly: 16.67,
        yearly: 200,
        quantity: null,
        inclusion: 'Workers Comp - Micro < $250K',
      },
      small: {
        code: '416442',
        monthly: 33.33,
        yearly: 400,
        quantity: null,
        inclusion: 'Workers Comp - Small < $500K',
      },
      medium: {
        code: '416443',
        monthly: 45.83,
        yearly: 550,
        quantity: null,
        inclusion: 'Workers Comp - Medium < $1M',
      },
      large: {
        code: '416444',
        monthly: 62.5,
        yearly: 750,
        quantity: null,
        inclusion: 'Workers Comp - Large < $3M',
      },
    },
    payrollProcessing: {
      salary: {
        code: null,
        monthly: 10,
        yearly: null,
        quantity: null,
        inclusion: 'Payroll processing per salaried employee',
      },
      timesheets: {
        code: null,
        monthly: 15,
        yearly: null,
        quantity: null,
        inclusion: 'Payroll processing per timesheet employee',
      },
    },
    payrollTaxReturns: {
      medium: {
        code: '416446',
        monthly: 16.67,
        yearly: 200,
        quantity: null,
        inclusion: 'Payroll Tax - Medium < $1M',
      },
      large: {
        code: '416447',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Payroll Tax - Large < $3M',
      },
    },
    superPrepAndLodgement: {
      micro: {
        code: '416449',
        monthly: 8.33,
        yearly: 100,
        quantity: null,
        inclusion: 'Super Prep and Lodgement - Micro < $250K',
      },
      small: {
        code: '416450',
        monthly: 12.5,
        yearly: 150,
        quantity: null,
        inclusion: 'Super Prep and Lodgement - Small < $500K',
      },
      medium: {
        code: '416451',
        monthly: 20.83,
        yearly: 250,
        quantity: null,
        inclusion: 'Super Prep and Lodgement - Medium < $1M',
      },
      large: {
        code: '416452',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Super Prep and Lodgement - Large < $3M',
      },
    },
    stpReporting: {
      micro: {
        code: '416454',
        monthly: 8.33,
        yearly: 100,
        quantity: null,
        inclusion: 'STP Reporting - Micro < $250K',
      },
      small: {
        code: '416455',
        monthly: 12.5,
        yearly: 150,
        quantity: null,
        inclusion: 'STP Reporting - Small < $500K',
      },
      medium: {
        code: '416456',
        monthly: 20.83,
        yearly: 250,
        quantity: null,
        inclusion: 'STP Reporting - Medium < $1M',
      },
      large: {
        code: '416457',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'STP Reporting - Large < $3M',
      },
    },
    lslReporting: {
      micro: {
        code: '416459',
        monthly: 12.5,
        yearly: 150,
        quantity: null,
        inclusion: 'LSL Construction Reporting - Micro < $250K',
      },
      small: {
        code: '416460',
        monthly: 12.5,
        yearly: 150,
        quantity: null,
        inclusion: 'LSL Construction Reporting - Small < $500K',
      },
      medium: {
        code: '416461',
        monthly: 20.83,
        yearly: 250,
        quantity: null,
        inclusion: 'LSL Construction Reporting - Medium < $1M',
      },
      large: {
        code: '416462',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'LSL Construction Reporting - Large < $3M',
      },
    },
  },
  advisoryServices: {
    taxPlanningReview: {
      micro: {
        code: '416464',
        monthly: 33.33,
        yearly: 400,
        quantity: null,
        inclusion: 'Tax Planning / Review - Micro < $250K',
      },
      small: {
        code: '416465',
        monthly: 50,
        yearly: 600,
        quantity: null,
        inclusion: 'Tax Planning / Review - Small < $500K',
      },
      medium: {
        code: '416466',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Tax Planning / Review - Medium < $1M',
      },
      large: {
        code: '416467',
        monthly: 166.67,
        yearly: 2000,
        quantity: null,
        inclusion: 'Tax Planning / Review - Large < $3M',
      },
    },
    taxStructuringAdvice: {
      micro: {
        code: '416469',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Tax Structuring Advice - Micro < $250K',
      },
      small: {
        code: '416470',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Tax Structuring Advice - Small < $500K',
      },
      medium: {
        code: '416471',
        monthly: 166.67,
        yearly: 2000,
        quantity: null,
        inclusion: 'Tax Structuring Advice - Medium < $1M',
      },
      large: {
        code: '416472',
        monthly: 416.67,
        yearly: 5000,
        quantity: null,
        inclusion: 'Tax Structuring Advice - Large < $3M',
      },
    },
    xeroSetup: {
      micro: {
        code: '416474',
        monthly: 62.5,
        yearly: 750,
        quantity: null,
        inclusion: 'Xero Setup - Micro < $250K',
      },
      small: {
        code: '416475',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Xero Setup - Small < $500K',
      },
      medium: {
        code: '416476',
        monthly: 125,
        yearly: 1500,
        quantity: null,
        inclusion: 'Xero Setup - Medium < $1M',
      },
      large: {
        code: '416477',
        monthly: 125,
        yearly: 1500,
        quantity: null,
        inclusion: 'Xero Setup - Large < $3M',
      },
    },
    xeroTraining: {
      micro: {
        code: '416479',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Xero Training - Micro < $250K',
      },
      small: {
        code: '416480',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Xero Training - Small < $500K',
      },
      medium: {
        code: '416481',
        monthly: 66.67,
        yearly: 800,
        quantity: null,
        inclusion: 'Xero Training - Medium < $1M',
      },
      large: {
        code: '416482',
        monthly: 100,
        yearly: 1200,
        quantity: null,
        inclusion: 'Xero Training - Large < $3M',
      },
    },
  },
  reporting: {
    financialStatementsTax: {
      micro: {
        code: '416484',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Financial Statements - Micro < $250K',
      },
      small: {
        code: '416485',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Financial Statements - Small < $500K',
      },
      medium: {
        code: '416486',
        monthly: 125,
        yearly: 1500,
        quantity: null,
        inclusion: 'Financial Statements - Medium < $1M',
      },
      large: {
        code: '416487',
        monthly: 166.67,
        yearly: 2000,
        quantity: null,
        inclusion: 'Financial Statements - Large < $3M',
      },
    },
    statutoryFinancialStatements: {
      large: {
        code: '416489',
        monthly: 250,
        yearly: 3000,
        quantity: null,
        inclusion: 'Statutory Financial Statements - Large < $3M',
      },
    },
    managementFinancialStatements: {
      micro: {
        code: '416491',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Management Financial Statements - Micro < $250K',
      },
      small: {
        code: '416492',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Management Financial Statements - Small < $500K',
      },
      medium: {
        code: '416493',
        monthly: 125,
        yearly: 1500,
        quantity: null,
        inclusion: 'Management Financial Statements - Medium < $1M',
      },
      large: {
        code: '416494',
        monthly: 166.67,
        yearly: 2000,
        quantity: null,
        inclusion: 'Management Financial Statements - Large < $3M',
      },
    },
  },
  meetings: {
    reviewNumbers: {
      micro: {
        code: '416496',
        monthly: 16.67,
        yearly: 200,
        quantity: null,
        inclusion: 'Review The Numbers Meetings - Micro < $250K',
      },
      small: {
        code: '416497',
        monthly: 25,
        yearly: 300,
        quantity: null,
        inclusion: 'Review The Numbers Meetings - Small < $500K',
      },
      medium: {
        code: '416498',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Review The Numbers Meetings - Medium < $1M',
      },
      large: {
        code: '416499',
        monthly: 62.5,
        yearly: 750,
        quantity: null,
        inclusion: 'Review The Numbers Meetings - Large < $3M',
      },
    },
    annualTaxMeetings: {
      micro: {
        code: '416501',
        monthly: 16.67,
        yearly: 200,
        quantity: null,
        inclusion: 'Annual Meetings - Micro < $250K',
      },
      small: {
        code: '416502',
        monthly: 25,
        yearly: 300,
        quantity: null,
        inclusion: 'Annual Meetings - Small < $500K',
      },
      medium: {
        code: '416503',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Annual Meetings - Medium < $1M',
      },
      large: {
        code: '416504',
        monthly: 62.5,
        yearly: 750,
        quantity: null,
        inclusion: 'Annual Meetings - Large < $3M',
      },
    },
  },
  supportServices: {
    teamOrEmail: {
      micro: {
        code: '416506',
        monthly: 20.83,
        yearly: 250,
        quantity: null,
        inclusion: 'Team or Email - Micro < $250K',
      },
      small: {
        code: '416507',
        monthly: 20.83,
        yearly: 250,
        quantity: null,
        inclusion: 'Team or Email - Small < $500K',
      },
      medium: {
        code: '416508',
        monthly: 33.33,
        yearly: 400,
        quantity: null,
        inclusion: 'Team or Email - Medium < $1M',
      },
      large: {
        code: '416509',
        monthly: 50,
        yearly: 600,
        quantity: null,
        inclusion: 'Team or Email - Large < $3M',
      },
    },
    clientServiceManager: {
      micro: {
        code: '416511',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Client Service Manager - Micro < $250K',
      },
      small: {
        code: '416512',
        monthly: 41.67,
        yearly: 500,
        quantity: null,
        inclusion: 'Client Service Manager - Small < $500K',
      },
      medium: {
        code: '416513',
        monthly: 50,
        yearly: 600,
        quantity: null,
        inclusion: 'Client Service Manager - Medium < $1M',
      },
      large: {
        code: '416514',
        monthly: 100,
        yearly: 1200,
        quantity: null,
        inclusion: 'Client Service Manager - Large < $3M',
      },
    },
    principalOwner: {
      micro: {
        code: '416516',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Principal / Owner - Micro < $250K',
      },
      small: {
        code: '416517',
        monthly: 83.33,
        yearly: 1000,
        quantity: null,
        inclusion: 'Principal / Owner - Small < $500K',
      },
      medium: {
        code: '416518',
        monthly: 125,
        yearly: 1500,
        quantity: null,
        inclusion: 'Principal / Owner - Medium < $1M',
      },
      large: {
        code: '416519',
        monthly: 208.33,
        yearly: 2500,
        quantity: null,
        inclusion: 'Principal / Owner - Large < $3M',
      },
    },
  },
};
